
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 05 14:03:43 BRT 2016
//----------------------------------------------------

package analisador;

/** CUP generated interface containing symbol constants. */
public interface iSimbolo {
  /* terminals */
  public static final int CONS = 3;
  public static final int FUNCTION = 7;
  public static final int MULT = 25;
  public static final int UMINUS = 28;
  public static final int LPAREN = 17;
  public static final int INT = 5;
  public static final int MINUS = 24;
  public static final int RPAREN = 18;
  public static final int BOOLEAN_LITERAL = 36;
  public static final int REAL_LITERAL = 35;
  public static final int NOT = 33;
  public static final int SEMICOLON = 19;
  public static final int AND = 31;
  public static final int LT = 29;
  public static final int OR = 32;
  public static final int COMMA = 20;
  public static final int DIV = 26;
  public static final int PLUS = 23;
  public static final int IF = 9;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int error = 1;
  public static final int EQEQ = 22;
  public static final int MOD = 27;
  public static final int EQ = 21;
  public static final int LBRACK = 13;
  public static final int REAL = 6;
  public static final int LBRACE = 15;
  public static final int ELSE = 11;
  public static final int RBRACK = 14;
  public static final int WHILE = 12;
  public static final int THEN = 10;
  public static final int RBRACE = 16;
  public static final int GT = 30;
  public static final int VAR = 2;
  public static final int PROCEDURE = 8;
  public static final int IDENTIFIER = 37;
  public static final int INTEGER_LITERAL = 34;
}

