
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 29 20:03:51 BRT 2016
//----------------------------------------------------

package analisador_lexico;

/** CUP generated interface containing symbol constants. */
public interface iSimbolo {
  /* terminals */
  public static final int SHORT = 10;
  public static final int IDENTIFIER = 104;
  public static final int ANDEQ = 96;
  public static final int REAL = 3;
  public static final int GT = 76;
  public static final int IMPLEMENTS = 42;
  public static final int CONST = 107;
  public static final int STRICTFP = 106;
  public static final int NOTEQ = 81;
  public static final int PLUSEQ = 91;
  public static final int RBRACK = 17;
  public static final int CONS = 4;
  public static final int CATCH = 61;
  public static final int COMMA = 21;
  public static final int RBRACE = 23;
  public static final int THROW = 59;
  public static final int RPAREN = 26;
  public static final int LBRACK = 16;
  public static final int LT = 75;
  public static final int ANDAND = 85;
  public static final int OROR = 86;
  public static final int DOUBLE = 15;
  public static final int LBRACE = 22;
  public static final int TRANSIENT = 38;
  public static final int LPAREN = 25;
  public static final int XOREQ = 97;
  public static final int PROTECTED = 31;
  public static final int INTEGER_LITERAL = 99;
  public static final int NOT = 69;
  public static final int VAR = 2;
  public static final int FINAL = 35;
  public static final int FLOAT = 14;
  public static final int GOTO = 108;
  public static final int THEN = 7;
  public static final int URSHIFTEQ = 95;
  public static final int PACKAGE = 28;
  public static final int COMP = 68;
  public static final int EQ = 24;
  public static final int BOOLEAN_LITERAL = 101;
  public static final int MOD = 71;
  public static final int CLASS = 40;
  public static final int SUPER = 46;
  public static final int ABSTRACT = 34;
  public static final int NATIVE = 36;
  public static final int LONG = 12;
  public static final int PLUS = 66;
  public static final int QUESTION = 87;
  public static final int WHILE = 54;
  public static final int EXTENDS = 41;
  public static final int INTERFACE = 47;
  public static final int CHAR = 13;
  public static final int BOOLEAN = 8;
  public static final int SWITCH = 50;
  public static final int DO = 53;
  public static final int FOR = 55;
  public static final int RSHIFTEQ = 94;
  public static final int VOID = 43;
  public static final int DIV = 70;
  public static final int PUBLIC = 30;
  public static final int RETURN = 58;
  public static final int MULT = 20;
  public static final int ELSE = 49;
  public static final int TRY = 60;
  public static final int GTEQ = 78;
  public static final int BREAK = 56;
  public static final int DOT = 18;
  public static final int PROCEDURE = 6;
  public static final int INT = 11;
  public static final int NULL_LITERAL = 105;
  public static final int THROWS = 44;
  public static final int STRING_LITERAL = 103;
  public static final int EQEQ = 80;
  public static final int EOF = 0;
  public static final int SEMICOLON = 19;
  public static final int THIS = 45;
  public static final int DEFAULT = 52;
  public static final int FUNCTION = 5;
  public static final int MULTEQ = 88;
  public static final int IMPORT = 29;
  public static final int MINUS = 67;
  public static final int LTEQ = 77;
  public static final int OR = 84;
  public static final int URSHIFT = 74;
  public static final int error = 1;
  public static final int SYNCHRONIZED = 37;
  public static final int DIVEQ = 89;
  public static final int LSHIFTEQ = 93;
  public static final int FINALLY = 62;
  public static final int CONTINUE = 57;
  public static final int INSTANCEOF = 79;
  public static final int IF = 48;
  public static final int MODEQ = 90;
  public static final int MINUSMINUS = 65;
  public static final int COLON = 27;
  public static final int CHARACTER_LITERAL = 102;
  public static final int OREQ = 98;
  public static final int VOLATILE = 39;
  public static final int CASE = 51;
  public static final int PLUSPLUS = 64;
  public static final int NEW = 63;
  public static final int RSHIFT = 73;
  public static final int BYTE = 9;
  public static final int AND = 82;
  public static final int PRIVATE = 32;
  public static final int STATIC = 33;
  public static final int LSHIFT = 72;
  public static final int XOR = 83;
  public static final int FLOATING_POINT_LITERAL = 100;
  public static final int MINUSEQ = 92;
}

