
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Sep 30 16:03:32 BRT 2016
//----------------------------------------------------

package analisador_lexico;

/** CUP generated interface containing symbol constants. */
public interface iSimbolo {
  /* terminals */
  public static final int CONS = 3;
  public static final int STRING_LITERAL = 37;
  public static final int FUNCTION = 12;
  public static final int MULT = 16;
  public static final int LPAREN = 21;
  public static final int INT = 5;
  public static final int MINUS = 24;
  public static final int RPAREN = 22;
  public static final int BOOLEAN_LITERAL = 35;
  public static final int CHARACTER_LITERAL = 36;
  public static final int NOT = 25;
  public static final int SEMICOLON = 15;
  public static final int AND = 31;
  public static final int LT = 28;
  public static final int OR = 32;
  public static final int COMMA = 17;
  public static final int DIV = 26;
  public static final int PLUS = 23;
  public static final int IF = 7;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int error = 1;
  public static final int EQEQ = 30;
  public static final int MOD = 27;
  public static final int EQ = 20;
  public static final int LBRACK = 13;
  public static final int REAL = 6;
  public static final int FLOATING_POINT_LITERAL = 34;
  public static final int LBRACE = 18;
  public static final int ELSE = 9;
  public static final int RBRACK = 14;
  public static final int WHILE = 10;
  public static final int THEN = 8;
  public static final int RBRACE = 19;
  public static final int GT = 29;
  public static final int VAR = 2;
  public static final int PROCEDURE = 11;
  public static final int IDENTIFIER = 38;
  public static final int INTEGER_LITERAL = 33;
}

